spring.application.name=Ecommerce_Project
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
## Used for elastic bean
#spring.jpa.properties.hibernate.format_sql=true
project.image=images/
spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationMs=${JWT_EXPIRATION_MS}
spring.ecom.app.jwtCookieName=SpringBootEcom
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.sql=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.project=DEBUG
frontend.url=${FRONTEND_URL}
image.base.url=http://localhost:8080/images
Stripe.secret.key=${STRIP_SECRET_KEY}
